#!/usr/bin/env bash
set -e

GREEN="\033[0;32m"
RED="\033[0;31m"
NC="\033[0m"

echo -e ${GREEN}Installing ${RED}forgeup${GREEN} to ${RED}/usr/local/bin${GREEN}!${NC}

FORGEUP='#!/usr/bin/env bash
set -e

GREEN="\033[0;32m"
RED="\033[0;31m"
NC="\033[0m"

if [[ "$1" == *foundry* || "$1" == *dapptools-rs*  ]]
then
    REPO=$1
    BRANCH=${2-master}
else
    REPO="gakonst/foundry"
    BRANCH=${1-master}
fi

echo -e ${GREEN}Updating ${RED}forge${GREEN} to ${RED}${REPO}${GREEN} at branch ${RED}${BRANCH}${GREEN}!${NC}


FOUNDRY_PATH="$HOME/.foundry"
REPO_PATH="$FOUNDRY_PATH/${REPO}"
mkdir -p $FOUNDRY_PATH

# if the repo path exists, just move to it, git pull, and checkout the branch
# then cargo install local
if [ -d $REPO_PATH ]
then
    cd $REPO_PATH
    git pull
    git checkout ${BRANCH}
    cargo install --path ./cli --bins --locked --force
else
    # repo path didnt exist, grab the author from the repo,
    # make a directory in .foundry, cd to it, clone and install
    IFS="/" read -ra AUTHOR <<< "$REPO"
    mkdir -p "$FOUNDRY_PATH/$AUTHOR"
    cd "$FOUNDRY_PATH/$AUTHOR"
    git clone https://github.com/${REPO}
    cd $REPO_PATH
    git checkout ${BRANCH}
    cargo install --path ./cli --bins --locked --force
fi'

BINARY="/usr/local/bin/forgeup"
echo "$FORGEUP" > $BINARY
chmod +x $BINARY
