#!/usr/bin/env bash
set -e

GREEN="\033[0;32m"
RED="\033[0;31m"
NC="\033[0m"

echo -e ${GREEN}Installing ${RED}forgeup${GREEN} to ${RED}/usr/local/bin${GREEN}!${NC}

FORGEUP='#!/usr/bin/env bash
set -e

GREEN="\033[0;32m"
RED="\033[0;31m"
NC="\033[0m"

if [[ "$1" == *foundry* || "$1" == *dapptools-rs*  ]]
then
    REPO=$1
    BRANCH=${2-master}
else
    REPO="gakonst/foundry"
    BRANCH=${1-master}
fi

echo -e ${GREEN}Updating ${RED}forge${GREEN} to ${RED}${REPO}${GREEN} at branch ${RED}${BRANCH}${GREEN}!${NC}


FOUNDRY_PATH="$HOME/.foundry"
REPO_PATH="$FOUNDRY_PATH/${REPO}"
mkdir -p $FOUNDRY_PATH

# if the repo path exists, just move to it, git pull, and checkout the branch
# then cargo install local
if [ -d $REPO_PATH ]
then
    cd $REPO_PATH
    git pull
    git checkout ${BRANCH}
    git pull
    cargo install --path ./cli --bins --locked --force
else
    # repo path didnt exist, grab the author from the repo,
    # make a directory in .foundry, cd to it, clone and install
    IFS="/" read -ra AUTHOR <<< "$REPO"
    mkdir -p "$FOUNDRY_PATH/$AUTHOR"
    cd "$FOUNDRY_PATH/$AUTHOR"
    git clone https://github.com/${REPO}
    cd $REPO_PATH
    git checkout ${BRANCH}
    cargo install --path ./cli --bins --locked --force
fi'

# Directory config
FORGE_DIR="$HOME/.forgeup"
BINARY="$FORGE_DIR/forgeup"

# Create the .forgeup directory and binary file if it doesn't exist
mkdir -p $FORGE_DIR
echo "$FORGEUP" > $BINARY
chmod +x $BINARY

# Store the correct profile file (e.g. .profile for bash or .zshrc for ZSH)
case $SHELL in
*/zsh) 
   echo "Detected your preferred shell is ZSH, adding forgeup to '.zshrc'. Please run 'source ~/.zshrc' after this script runs, or start a new terminal session to use forgeup."
   PROFILE=$HOME/.zshrc
   ;;
*/bash)
   PROFILE=$HOME/.profile
   source $PROFILE
   ;;
*)
   echo "Error: could not detect shell, please manually add $FORGE_DIR to your PATH variable!"
   exit 1
esac

# Only add the forgeup directory to profile if it isn't in path
if [[ ":$PATH:" != *":$HOME/.forgeup:"* ]]; then
    # Add the forgeup directory to the path and source it
    echo "export PATH=$PATH:$FORGE_DIR" >> $PROFILE
fi

# Source the updated profile if we are in bash
if [[ "$SHELL" == *"bash"* ]]; then
   source $PROFILE
fi
